from random import shuffle

supported_languages=[

]


dyn="dyn"  
code="media"
questions1 = [
    "Why are you making this presentation?",
    "What does spirituality mean to you?",
    "What is actually different now?",
    "How long do I want to keep working for Dyn?",
    "How are you all doing today?",
    "What is my favorite food?",
    "What is the best Slovenian food?",
    "What did you do in Slovenia?",
    "What is your favorite sport?",
    "What is your favorite firma (company)?",
    "What would help humanity the most?",
    "Is money the answer to all problems or all solutions?",
    "What is a life, in your opinion?",
    "What was the hardest part about walking barefoot?",
    "Why is manipulation bad?",
    "What do you think is the most important problem in today's society?",
    "Can you prove that 1=2?",
    "Was mathematics invented or discovered?",
    "What would be a good question to ask in this presentation?",
    "Is AI conscious?",
    "Do we care if AI is conscious?",
    "Can this presentation be over now?",
    "Can I please excuse myself? I need to do something else; I can't listen to this presentation."
]

questions2 = [
    "What is, in your opinion, ego death?",
    "Where can I learn more about ego death?",
    "What does it mean to be enlightened?",
    "How did Jesus do his magic tricks?",
    "What is your favorite firma (company)?",
    "What would be a good question to ask in this presentation?",
    "What was the salary in your previous company?",
    "How does ego death feel like?",
    "Did you ever answer untruthfully?",
    "Are cats better than dogs?",
    "What do you think of Deutschland Ticket?",
    "Why did Jesus have 12 apostles and not 10, for example?",
    "Why are some questions so offensive?",
    "Did we really kill God?",
    "What is your secret fetish?",
    "Where does God actually live?",
    "Are you really going to tell us everything?",
    "Why is clicking on those questions so addicting?",
    "I don't like this anymore; can I leave?",
    "When does this presentation end?",
    "Why are some questions not really questions?",
    "Can I see a list of all the questions?",
    "Do you have something in between your teeth?",
    "Are you going to answer all of the questions?",
    "Do you still want to work for this company?",
    "Are the questions repeating?"
    "Which religion you think is the best?"
]
questions3 = [
    "Why do you have new glasses?",
    "Did you grow taller?",
    "Why is your hair gone?",
    "Was this generated by AI?",
    "I know it was not, but I am human, and I want to help other humans like real help.",
    "Who bought you a new phone?",
    "What happened to your own phone?",
    "Why do you have trouble accessing 2FA?",
    "Did you really do all of those things? Yes, I did.",
    "Why did you escape the psych ward?",
    "Schizotypal vs. schizophrenia.",
    "Why is AI the best?",
    "Why can't I see all the answers?",
    "Do you feel happy now?",
    "What is actually different now?",
    "What is your salary?",
    "Are you going to answer every question?",
    "What was the hardest part about walking barefoot?",
    "Can you prove that 1=2?",
    "Was mathematics invented or discovered?",
    "What is something you would change at the company?",
    "Which company do you think is the best?",
    "What is the best thing about working at Dyn?",
    "How much does money mean for you?",
    "Can I see a list of all the questions?",
    "Are you going to answer all of the questions?",
    "How did you hack the neighbor's wifi?",
    "Are computers really random?",
    "Have you found the meaning of life?",
    "What is the meaning of life?",
    "Who helped you the most in this team?",
    "Are all the questions the same?",
    "Is Dyn media the answer for everything?",
    "Was war dein großes Problem wenn du nicht in Dyn wärst? (What was your big problem if you were not in Dyn?)",
    "How do you see yourself if everyone around you is mirrors?",
    "Do I need to ask those questions?",
    "Why are you presenting more as a 'man' now?"
]
infinite_questions = \
[
    "How many questions are there?",
    "Do those questions ever end?",
    "Do you know what infinity is?",
    "How many questions are there?",
    "I have no idea what I am doing?",
    "Why do I keep refreshing the page?",
    "Are there more quesions?",
    "Are there more quesions?",
    "Are there more quesions?",
    "...?",
]
infinite_questions2 = \
[
    "Are there more quesions?",
    "I have no idea what I am doing?",

]


magic_number1=len(infinite_questions)

goodQ = [("good", i) for i in questions1]
medQ = [("med", i) for i in questions2]
badQ = [("bad", i) for i in questions3]
inf = [("inf", i) for i in infinite_questions]
inf2 = [("inf2", i) for i in infinite_questions2]

qs = [goodQ, medQ, badQ, inf, inf2]
questions = []

for q in qs:
    shuffle(q)
    questions += q  



def get_questions_eng(num_questions, start):
    questions_inf = questions
    print(num_questions, start, len(questions_inf))
    while len(questions_inf) < start + num_questions:
        questions_inf += inf2

    shuffled = questions[start:start+num_questions]
    shuffle(shuffled) 
    return shuffled
    

def get_random_questions(how_many_time_asked):
    if how_many_time_asked > magic_number1:
        return infinite_questions + get_questions(2)


